use crate::types::{DetectionCategory, DeterministicNormalizationMode, DeterministicValidatorKind};

use super::{BuiltinFieldGateSpec, BuiltinRuleSpec};

pub(super) const BUILTIN_RULES: [BuiltinRuleSpec; 13] = [
    BuiltinRuleSpec { rule_id: "builtin.secrets.bearer_token", category: DetectionCategory::Secrets, priority: 470, pattern: r"(?i)\bbearer\s+(?:gh[pousr]_[a-z0-9]{20,}|eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+|[A-Za-z0-9._\-]{24,})\b", validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: None },
    BuiltinRuleSpec { rule_id: "builtin.secrets.secret_assignment", category: DetectionCategory::Secrets, priority: 468, pattern: r#"(?i)\b(?:token|secret|api[_-]?key|access[_-]?token|auth[_-]?token)\s*[:=]\s*['"]?(?:gh[pousr]_[a-z0-9]{20,}|sk[-_][a-z0-9][a-z0-9_-]{8,}|eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+|[A-Za-z0-9._\-]{24,})['"]?"#, validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: None },
    BuiltinRuleSpec { rule_id: "builtin.secrets.sk_api_key", category: DetectionCategory::Secrets, priority: 465, pattern: r"(?i)\bsk[-_][a-z0-9][a-z0-9_-]{8,}\b", validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: None },
    BuiltinRuleSpec { rule_id: "builtin.secrets.github_pat", category: DetectionCategory::Secrets, priority: 466, pattern: r"(?i)\bgh[pousr]_[a-z0-9]{20,}\b", validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: None },
    BuiltinRuleSpec { rule_id: "builtin.pii.email", category: DetectionCategory::Pii, priority: 320, pattern: r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}", validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: None },
    BuiltinRuleSpec { rule_id: "builtin.pii.url", category: DetectionCategory::Pii, priority: 319, pattern: r#"(?i)\b(?:https?|ftp)://[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+(?::\d{2,5})?(?:/[a-z0-9._~:/?#\[\]@!$&'()*+,;=%-]*[a-z0-9/#])?"#, validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: None },
    BuiltinRuleSpec { rule_id: "builtin.pii.ipv4", category: DetectionCategory::Pii, priority: 318, pattern: r"\b(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\.){3}(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)\b", validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: None },
    BuiltinRuleSpec { rule_id: "builtin.pii.phone", category: DetectionCategory::Pii, priority: 317, pattern: r"(?:(?:\+7|8)[ -]?(?:\(\d{3}\)|\d{3})[ -]?\d{3}(?:[ -]?\d{2}){2}|(?:\+?\d{1,3}[ -]?)?(?:\(?\d{3}\)?[ -]?)\d{3}[ -]?\d{4})", validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: None },
    BuiltinRuleSpec { rule_id: "builtin.pii.name_field", category: DetectionCategory::Pii, priority: 316, pattern: r"^[A-Za-zА-Яа-яЁё][A-Za-zА-Яа-яЁё'-]{0,63}$", validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: Some(BuiltinFieldGateSpec { json_pointer_suffixes: &["/first_name", "/last_name", "/middle_name", "/firstname", "/lastname", "/middlename", "/firstName", "/lastName", "/middleName"] }) },
    BuiltinRuleSpec { rule_id: "builtin.pii.person_identity_field", category: DetectionCategory::Pii, priority: 315, pattern: r"^(?:[a-z][a-z0-9]*(?:[._-][a-z0-9]+){1,}|[А-ЯЁ][а-яё]{1,30}\s+[А-ЯЁ][а-яё]{1,30}\s+[А-ЯЁ][а-яё]{1,30}(?:\s*\(\d{4,12}\))?)$", validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: Some(BuiltinFieldGateSpec { json_pointer_suffixes: &["/name", "/username"] }) },
    BuiltinRuleSpec { rule_id: "builtin.pii.person_id_field", category: DetectionCategory::Pii, priority: 314, pattern: r"^(?:[0-9]{6,20}|[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12})$", validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: Some(BuiltinFieldGateSpec { json_pointer_suffixes: &["/id"] }) },
    BuiltinRuleSpec { rule_id: "builtin.pii.card_number", category: DetectionCategory::Pii, priority: 310, pattern: r"\b\d(?:[ -]?\d){12,15}\b", validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: None },
    BuiltinRuleSpec { rule_id: "builtin.corporate.project_name", category: DetectionCategory::CorporateMarkers, priority: 220, pattern: r"(?i)\bproject\s+[a-z][a-z0-9_-]{2,}\b", validator: DeterministicValidatorKind::None, normalization: DeterministicNormalizationMode::Preserve, field_gate: None },
];
